[project]
name = "comfyui-ajonodes"
description = ""
version = "1.0.0"
license = {text = "MIT License"}

[project.urls]
Repository = "https://github.com/AJO-reading/ComfyUI-AjoNodes"
[tool.comfy]
PublisherId = "adamreading"
DisplayName = "ComfyUI-AjoNodes"
Icon = ""
