[project]
name = "comfyui-ajonodes"
description = ""
version = "1.0.0"
license = "MIT License"

[project.urls]
Repository = "https://github.com/AJO-reading/ComfyUI-AjoNodes"
[tool.comfy]
PublisherId = "AJO-reading"
DisplayName = "ComfyUI-AjoNodes"
Icon = ""
